name: Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test and build
        run: |
          docker build -t mateusgpedro/react-test ./client -f Dockerfile.dev
          docker run -e CI=true mateusgpedro/react-test npm test

      - name: Build project
        run: |
          docker build -t mateusgpedro/multi-client ../../client
          docker build -t mateusgpedro/multi-nginx ../../nginx
          docker build -t mateusgpedro/multi-server ../../server
          docker build -t mateusgpedro/multi-worker ../../worker
